"""created all the needed indexes

Revision ID: 4344a5ca16c0
Revises: 7831d902832b
Create Date: 2026-07-26 13:44:44.481888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4344a5ca16c0'
down_revision: Union[str, Sequence[str], None] = '7831d902832b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_food_item_sufficient_stock'), 'food_item', ['sufficient_stock'], unique=False)
    op.create_index(op.f('ix_food_item_purchases_date_purchased'), 'food_item_purchases', ['date_purchased'], unique=False)
    op.create_index(op.f('ix_food_item_purchases_food_item_id'), 'food_item_purchases', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_meal_plan_entries_plan_id'), 'meal_plan_entries', ['plan_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredient_ingredient_id'), 'recipe_ingredient', ['ingredient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredient_ingredient_id'), table_name='recipe_ingredient')
    op.drop_index(op.f('ix_meal_plan_entries_plan_id'), table_name='meal_plan_entries')
    op.drop_index(op.f('ix_food_item_purchases_food_item_id'), table_name='food_item_purchases')
    op.drop_index(op.f('ix_food_item_purchases_date_purchased'), table_name='food_item_purchases')
    op.drop_index(op.f('ix_food_item_sufficient_stock'), table_name='food_item')
    # ### end Alembic commands ###
