"""added index to meal_plan_entry.status

Revision ID: 68e2700e84d2
Revises: 4344a5ca16c0
Create Date: 2026-07-26 13:49:26.354520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68e2700e84d2'
down_revision: Union[str, Sequence[str], None] = '4344a5ca16c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_meal_plan_entries_status'), 'meal_plan_entries', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_plan_entries_status'), table_name='meal_plan_entries')
    # ### end Alembic commands ###
