"""baseline - food_items, ingredients, recipes, recipe_ingredients

Revision ID: c3a7a13948f5
Revises: 
Create Date: 2026-07-26 13:15:13.754934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3a7a13948f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_quantity', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('sufficient_stock', sa.Boolean(), server_default=sa.text('true'), nullable=True),
    sa.Column('serving_unit', sa.String(), nullable=True),
    sa.Column('calories', sa.Numeric(), nullable=True),
    sa.Column('serving_size', sa.Numeric(), nullable=True),
    sa.Column('protein_g', sa.Numeric(), nullable=True),
    sa.Column('carbs_g', sa.Numeric(), nullable=True),
    sa.Column('fat_g', sa.Numeric(), nullable=True),
    sa.Column('fiber_g', sa.Numeric(), nullable=True),
    sa.Column('sugar_g', sa.Numeric(), nullable=True),
    sa.Column('sodium_mg', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('instructions', sa.String(), nullable=True),
    sa.Column('meal_type', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('prep_time', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('nutrition', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=True),
    sa.Column('times_suggested', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('times_accepted', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('default_unit', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('food_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('recipe_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipes_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipes_id'], ['recipe.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredient')
    op.drop_table('ingredient')
    op.drop_table('recipe')
    op.drop_table('food_item')
    # ### end Alembic commands ###
